from .sites.dantri.selectors import (
    AUTH_TAB_SELECTOR,
    HEADER_ACCOUNT_BUTTON_SELECTOR,
    LOGIN_EMAIL_INPUT_SELECTOR,
    LOGIN_PASSWORD_INPUT_SELECTOR,
    LOGIN_SUBMIT_SELECTOR,
    LOGOUT_TEXT_CANDIDATES,
    NAVIGATION_BUTTON_SELECTOR,
    REACTION_CONTAINER_SELECTOR,
    REGISTER_NAME_INPUT_SELECTOR,
    REGISTER_SUBMIT_SELECTOR,
    USER_MENU_BUTTON_SELECTOR,
    VOTE_SECTION_TEXT,
)
